export const prompts: string[] = [
  "marine life, ocean creatures, sea animals, undersea world",
  "starry sky, galaxy, universe, space, nebula, cosmos",
  "abstract art, geometric, minimalism, modern art",
  "cityscape, night view, city lights, skyscrapers, neon lights",
  "autumn leaves, fall colors, foliage, golden autumn",
  "winter landscape, snowfall, snowflakes, frost, snow-covered",
  "van gogh starry night, post-impressionism, swirling stars",
  "ink wash painting, sumi-e, calligraphy, brushwork",
  "multicolored, colorful, vibrant, rainbow, vivid",
  "steampunk, gears, clockwork, victorian, industrial",
  "fairy magic, enchanted, pixie, fantasy, mystic",
  "forest sprites, woodland creatures, nature spirits",
  "technology lines, digital, circuitry, futuristic, hi-tech",
  "countryside, pastoral, rural landscape, fields, greenery",
  "wildlife, wild animals, safari, jungle, natural habitat",
  "3D geometry, polygons, geometric shapes, spatial",
  "ancient roman architecture, columns, arches, classical",
  "fashion trends, vogue, chic, couture, glamour",
  "balloon scenery, hot air balloon, aerial view, flight",
  "beachside, cozy cottage, sand, seashells, ocean view",
  "picnic, cherry blossom tree, spring, petals, flowers",
  "waterfall, hidden, lush jungle, greenery, mist, tranquil",
  "fantasy castle town, beautiful building, flowers, romantic",
  "coastal village, peaceful harbor, boats, fishing nets",
  "lavender field, summer, purple, calming, warm breeze",
  "jazz music, saxophone, rhythm, improvisation, swing",
  "portrait painting, fine art, oil painting, canvas",
  "ancient greek mythology, olympus, classical myths",
  "diamond facets, gemstone, sparkle, jewel, brilliance",
  "african tribal culture, masks, tribal art, folklore",
];
